from tools import functions as fn

# Finding each variable's parameter if unset

def find_cloud_field():
    fn.logger("Please choose Cloud's appearance in the field")
    fn.logger("0 = No Change")
    fn.logger("1 = WITHOUT sword")
    fn.logger("2 = WITH Buster sword")
    fn.logger("3 = Wielding Masamune")
    fn.logger("4 = Omni Cloud")
    fn.logger("5 = Squallff8's Rebuilded")
    fn.logger("6 = Grimmy's AC Style")
    fn.logger("7 = FMV with Sword (Weemus)")
    fn.logger("8 = FMV Without Sword (Weemus)")
    fn.logger("9 = Chibi Strife (NameSpoofer)")
    fn.logger("10 = APZ with Sword")
    fn.logger("11 = APZ without Sword")
    fn.logger("12 = APZ Black with Sword")
    fn.logger("13 = APZ Black without Sword")
    fn.logger("14 = APZ Dark with Sword")
    fn.logger("15 = APZ Dark without Sword")
    fn.logger("16 = APZ Chibi")
    fn.logger("17 = APZ Black Chibi")
    fn.logger("18 = APZ Dark Chibi")
    fn.logger("19 = BitzNCS New Chibi")
    fn.logger("20 = PRP Classic")
    fn.logger("21 = Chibi Reconstruction")
    fn.logger("22 = Dahfa's Chibi")
    fn.logger("23 = APZ Adjusted")
    fn.logger("24 = Team Avalanche Chibi")
    fn.logger("25 = Bloodshot's Edited TA")

def find_cloud_battle():
    fn.logger("0 = No Change")
    fn.logger("1 = Classic")
    fn.logger("2 = The Remix APZ")
    fn.logger("3 = Grimmy's Hi Res")
    fn.logger("4 = Grimmy's AC Style")
    fn.logger("5 = FMV Cloud (Weemus)")
    fn.logger("6 = Strife")
    fn.logger("7 = New APZ")
    fn.logger("8 = New APZ Black")
    fn.logger("9 = New APZ Dark")
    fn.logger("10 = New APZ Mature")
    fn.logger("11 = Team Avalanche")
    fn.logger("12 = Bloodshot's Edited TA")

