from tools.logger import help

# Finding each variable's parameter if unset

def find_cloud_field():
    help("Please choose Cloud's appearance in the field")
    help("0 = No Change")
    help("1 = WITHOUT sword")
    help("2 = WITH Buster sword")
    help("3 = Wielding Masamune")
    help("4 = Omni Cloud")
    help("5 = Squallff8's Rebuilded")
    help("6 = Grimmy's AC Style")
    help("7 = FMV with Sword (Weemus)")
    help("8 = FMV Without Sword (Weemus)")
    help("9 = Chibi Strife (NameSpoofer)")
    help("10 = APZ with Sword")
    help("11 = APZ without Sword")
    help("12 = APZ Black with Sword")
    help("13 = APZ Black without Sword")
    help("14 = APZ Dark with Sword")
    help("15 = APZ Dark without Sword")
    help("16 = APZ Chibi")
    help("17 = APZ Black Chibi")
    help("18 = APZ Dark Chibi")
    help("19 = BitzNCS New Chibi")
    help("20 = PRP Classic")
    help("21 = Chibi Reconstruction")
    help("22 = Dahfa's Chibi")
    help("23 = APZ Adjusted")
    help("24 = Team Avalanche Chibi")
    help("25 = Bloodshot's Edited TA")

def find_cloud_battle():
    help("0 = No Change")
    help("1 = Classic")
    help("2 = The Remix APZ")
    help("3 = Grimmy's Hi Res")
    help("4 = Grimmy's AC Style")
    help("5 = FMV Cloud (Weemus)")
    help("6 = Strife")
    help("7 = New APZ")
    help("8 = New APZ Black")
    help("9 = New APZ Dark")
    help("10 = New APZ Mature")
    help("11 = Team Avalanche")
    help("12 = Bloodshot's Edited TA")

